#cloud-config

# sets the hostname to represent the node
# hostname: ${vsphere_virtual_machine.node.name}
# fqdn: ${vsphere_virtual_machine.node.name}.sandbox.facelan.com

users:
# Adds a user called 'example' with the password hash of 'passwort', sudo rights and the default ubuntu groups
        - name: example
          passwd: $6$rounds=4096$P0uvlB9.8nsiY67$uuOxYSk6n/74Ds3JtV1mT6xYjOguwTWgNmOeHvcHiQa9zan57l8dvfHE/zlu19fDmJGySNzLmh6K0R2I1AU9o0
          lock_passwd: false 
          sudo: ALL=(ALL) ALL
          groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]

# Enable ssh password authentication
ssh_pwauth: True 

# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
#
# Default: false
package_update: true

# Upgrade the instance on first boot
#
# Default: false
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io



write_files:
  # Enable ipv4 forwarding, required on CIS hardened machines
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

runcmd:
  # - sudo apt-mark hold kubelet kubeadm kubectl
  # - systemctl enable container

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

snap:
  commands:
    - ['install', 'kubeadm', '--classic']
    - ['install', 'kubectl', '--classic']
    - ['install', 'kubelet', '--classic']
    - ['install', 'etcd']